name: Sanity backup
on:
  workflow_dispatch:
  schedule:
    # Midnight every day
    - cron: "* 0 * * *"
jobs:
  backup-dataset:
    runs-on: ubuntu-18.04
    name: Backup dataset
    steps:
      - uses: actions/checkout@v2
      - name: Export dataset
        uses: sanity-io/github-action-sanity@v0.2-alpha
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_DATASET_EDITOR_TOKEN }}
        with:
          args: dataset export production backups/backup.tar.gz
          working-directory: ./sanity
          workdir: ./sanity
      - name: Upload backup.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: backup-tarball
          path: backups/backup.tar.gz
          # Fails the workflow if no files are found; defaults to 'warn'
          if-no-files-found: error
